### ISSUE TITLE
Is there any documentation or demo how to use this ?

### ISSUE THREAD

**Issue by kabircse** [iSenseLabs/OpenCartAPI#4]
Is there any documentation or demo how to use this or call from another site using curl ?

**Comment by dtlgc** [comment]
Does this work with v2.3.02 ??

**Comment by raxbg** [comment]
>Is there any documentation or demo how to use this or call from another site using curl ?

No, not really. This is a library that can talk to OpenCart's API methods, but since the API is still not fully developed and only serves the needs of the order editing in OpenCart, the functionality that it exposes is pretty limited. To use this library you simply include it and then create an object of type OpenCart\OpenCart like this `$oc = new OpenCart\OpenCart(<store url>[, <path to a session persistence file if you need that]);`

You can then login like this `$oc->login(<username>, <api key>);`, or add items to the cart like this `$oc->cart->add(<product id>[, <quantity>[, <options>]]);`. You can find a list of all available methods in the readme.

>Does this work with v2.3.02 ??

Yes, since this commit 9fb8203.
