### ISSUE TITLE
Suggestion: custom() function for interacting with custom functions we add to OpenCart's API Class

### ISSUE THREAD

**Issue by twistedpixel** [iSenseLabs/OpenCartAPI#7]
Wondered what you thought about this. For example, I extended the OpenCart API on a few installations to include various additional functions based on our needs like 'order/get' (which fetches details of an order).

Might be nice to have a custom function for non-standard API endpoints. For example:

```
public function custom($url = null, $postData = array()) {
    if (empty($url)) throw new InvalidDataException("URL cannot be empty for Order->custom()");
    if (!is_array($postData) throw new InvalidDataException("postData must be an associative array for Order->custom()");
    if (empty($postData['order_id']) throw new InvalidDataException("postData['order_id'] is required for for Order->custom()");

    $this->curl->setUrl($this->oc->getUrl($url.'&order_id='.$postData['order_id']));
    $this->curl->setData($postData);
    $this->curl->makeRequest();

    return $this->curl->getResponse();
}
```

You may find this a bit of a rare use-case but it could be useful if OpenCart adds additional endpoints that people need and these bindings aren't updated immediately. Gives us a fallback.

I'd be happy to submit a pull request for this if you're interested.

**Comment by raxbg** [comment]
Sounds reasonable to have this. Please take a look at this commit https://github.com/iSenseLabs/OpenCartAPI/commit/bdeb63d78f91cfa77b4837db49dcaa58f8a744d7. It is pretty much what you are requesting, but instead of having a predefined `custom()` function we are using the `__get()` and `__call()` methods to support non-defined/custom endpoints. For example if you want to call 'order/get', you would simply do `$opencart->order->get($postData);`. Any custom method can be called that way. Suppose you added this endpoint 'category/getProducts', then you can access it like this `$opencart->category->getProducts(array('category_id' => 5));`.

Having implemented it that way, will make more sense when reading the code that uses this library. Let me know whether you think this would work, so I can merge it into master.

**Comment by twistedpixel** [comment]
Just looked over your commit. That is very cool and a much better solution.

I've never used magic functions or overloading so thanks for the prompt to learn something new!

Edit: Oh and yes, please go ahead and merge. If I run into any issues I'll re-open this issue.

**Comment by twistedpixel** [comment]
Minor bug in the new custom methods implementation. On line 112 (function `__call()`) `$postData` is actually received as an enumerated array of arguments - seems that's the way `__call()` works. Not sure of the cleanest way to solve this but for now I'm just adding `$postData = $postData[0]` on line 107.

I don't really see a better way round it because there's no need to handle additional arguments since the first argument is being passed as an array: `$opencart->order->get(array('order_id' => $order_id));`

Can you think of a better solution?

**Comment by raxbg** [comment]
Not really, I think what you are suggesting is okay, just have to rename the `$postData` argument of the `_call()` function to `$args` and then on line 107 do `$postData = $args[0]` for better readability. 

Please send a pull request with the change so I can merge it.

**Comment by twistedpixel** [comment]
Done.

Never done a pull request before so let me know if I've done anything wrong. Closing this issue again.
